### PR TITLE
Mention guix package

### PR DESCRIPTION
**Pull request by jgarte**

### CODE REVIEW

**Comment by sewnie** [comment]
This project is abandoned.

https://github.com/aome510/spotify-player

**Comment by jgarte** [comment]
> This project is abandoned.
> 
> https://github.com/aome510/spotify-player

Thanks for the update!

Closing.

**Comment by sewnie** [comment]
Also damn stop distrohopping, I see you on void, oasis, kiss, guix, nix

**Comment by jgarte** [comment]
> Also damn stop distrohopping, I see you on void, oasis, kiss, guix, nix

i have just one love now[...](https://git.sr.ht/~whereiseveryone/confetti)

https://issues.guix.gnu.org/62440

**Comment by apteryks** [comment]
Hi! 

If this project is truly abandoned, could its repository please be archived to communicate it as such?

Thanks!

**Comment by jgarte** [comment]
@Rigellute WDYT

**Comment by sewnie** [comment]
Despite rigellute announcing that they will update the project, it has been months and its been untouched.

The last we can do is do it by word.

**Pull request closed without merging**
