### PR TITLE
Add Ctrl-f and Ctrl-b emacs style keybindings for left and right motion

### PR DESCRIPTION
**Pull request by RadicalZephyr**
It seems unfair to leave out the emacs keybindings for left and right motion, so I added them for you.

### CODE REVIEW

**Comment by RadicalZephyr** [comment]
Sure thing! I also added similar documentation for the up and down movement as well.

**Comment by RadicalZephyr** [comment]
I think I fixed it.  That's a neat CI check for formatting you have. I might need to borrow that for my own Rust projects...

**Comment by Rigellute** [comment]
@RadicalZephyr feel free to use both CI and CD scripts! https://github.com/Rigellute/spotify-tui/blob/master/.github/workflows/

GitHub actions is working really well.

**Comment by Rigellute** [comment]
@all-contributors please add @RadicalZephyr for code

**Pull request merged**
