### PR TITLE
Import snap files, preparation for snap builds and deploys on travis via snap remote builds

### PR DESCRIPTION
**Pull request by hurricanehrndz**
These commits need to be merged before Travis and remote builds can be enable.
In order to enable the remote builds I will need to forward you some secrets and a couple of steps that will need be run in order to setup auto publishing from Travis on tags. Please let me know the best method to forward this to you.

For now we are using the spt-temp namespace, but I have opened a request for spt.

### CODE REVIEW

**Comment by hurricanehrndz** [comment]
See a sample: https://travis-ci.org/hurricanehrndz/spotify-tui

**Comment by Rigellute** [comment]
Great stuff! Thank you! 
I wonder if we can use the [existing github Actions continuous deployment](https://github.com/Rigellute/spotify-tui/blob/master/.github/workflows/cd.yml) to auto publish?
Or do we need to use Travis?

**Comment by hurricanehrndz** [comment]
I'll look into it and get back to you. The Travis stuff was kept seperate
in case you made this request. I will work something out, but this should
have no implication on whether this can be merged or not.

**Comment by Rigellute** [comment]
@all-contributors please add @hurricanehrndz for platform

**Comment by hurricanehrndz** [comment]
Alex,

What is the best method to get secrets to you?

**Comment by Rigellute** [comment]
@hurricanehrndz let's chat over on email rigellute@gmail.com

**Pull request merged**
