### PR TITLE
Load playlist listing greedily

### LINKED ISSUE #116: Playlist section not complete
So the playlist section is missing playlists. From the looks of it the playlist api only returns 20 playlists by default. Adding limit=50 to the query will increase it to 50 however in my case I have 70 playlists. In which case paging will need to be implemented. Overwise great job I really enjoy it.

### PR DESCRIPTION
**Pull request by jackkinsey**
Fixes #116. 

This change defies the pagination model the rest of the application seems to be using, requesting pages of playlists until all playlists have been loaded. (It's also slightly hacky in doing so.) 

I totally understand if you don't want to go this route with the app, but I figured I might as well show up with some working code to get the conversation started. (Obligatory note about being a Rust beginner/apologies if my code isn't idiomatic.)

Thanks for making this! It's super cool, I look forward to using it more.

### CODE REVIEW

**Comment by Rigellute** [comment]
Thanks for taking a crack at this @jackkinsey.

I'd prefer us to not greedily load all tracks in a playlist.

Pagination is a tricky one to solve and that is part of the reason not all views implement it currently. 

I need to sit down and have a rethink to hopefully find a more generic solution.

Anyway, appreciate your effort here. And for what it's worth your code looks good!

**Comment by jackkinsey** [comment]
Just to be clear: this change doesn't load all the *tracks in a playlist*, it loads all the *playlists in the playlist listing*, in the sidebar.

**Comment by Rigellute** [comment]
Thanks for the clarification @jackkinsey. 

I meant to say I want us to avoid greedy loading of any paginated response.

Anyway, thanks again for your efforts. 

I will close this and try to find a better generic solution for handling pagination.

**Comment by jradek** [comment]
Hi,
I've version 0.21.0 on MacOS and the problem is somehow still there.
Only a fraction of all my playlists are shown and ctrl-d / ctrl-u don't work. j/k just cycle through the first result page.
Could it be a regression?

JR

**Comment by j-hui** [comment]
@Rigellute Could you explain more about your opposition to this particular workaround? This might not be a generic solution that solves the issue of pagination once and for all, but at least it helps us see playlists we currently simply cannot see (:

**Comment by j-hui** [comment]
@jradek I think the `<C-d>` and `<C-u>` bindings are specifically used cycling through pages of songs _within a playlist_ (rather than cycling through pages of the _list of playlists_). This PR specifically deals with the list of playlists.

**Pull request closed without merging**
