### PR TITLE
Bump versions in Cargo.lock.

### PR DESCRIPTION
**Pull request by tem1029**
The app would hang upon trying to authenticate with Spotify
on FreeBSD, bumping the versions to the latest seems to have
fixed this issue. All tests pass and works as expected.

### CODE REVIEW

**Comment by tem1029** [comment]
Any update on this? I've simply ran ``cargo update`` and that fixed the issue on FreeBSD, where during the process of opening the browsing then authenticating it would hang, of which seemed to be fixed by updating the packages deps, subsequently fixing that issue.

**Comment by tem1029** [comment]
Awesome, thanks. When you've pushed a new tag I'll be resubmitting a FreeBSD port that I sent in a while back (but unfortunately at the time wouldn't work to the now fixed issue). :+1:

**Comment by Rigellute** [comment]
If you know how we can add a package manager for FreeBSD (or any other linux distros), please let me know!

**Comment by tem1029** [comment]
There seems to be this in the Arch Linux community repository ( https://aur.archlinux.org/packages/spotify-tui/ ), although I'm not sure the status of other Linux distros. Might be worth nothing this in the README or something similar as an alternative installation method.

**Pull request merged**
