### PR TITLE
Confirm delete

### LINKED ISSUE #384: Prompt to confirm playlist delete
It is far too easy to delete a playlist by accidentally typing D.
The user should be prompted for confirmation before actually deleting the playlist.

### PR DESCRIPTION
**Pull request by ilnaes**
Screen Shot 2020-04-16 at 8 50 57 AM

Added some support for future confirmation dialogs, also.
Closes #384

### CODE REVIEW

**Comment by slumber** [comment]
I cloned your branch and rebased it to master, here are my notes:
1. I couldn't really get it to work, there is a pop up window, but after pressing Ok/Cancel nothing happens, selected playlist wouldn't go away.
2. Pressing Esc while deciding whether to unfollow or not is broken, if you then press Enter in brings up the window again, and hovering between frames wouldn't work until you press 'q'.
3. I guess it's reasonable to prompt users when they unfollow a playlist from search results. See https://github.com/Rigellute/spotify-tui/pull/399

**Comment by ilnaes** [comment]
Thanks for the check!  A hasty last minute addition broke the actual unfollowing.  I fixed those issues along with the clippy issues.

**Comment by Rigellute** [comment]
Great work @ilnaes, just tested out your branch and it looks awesome!

**Comment by Rigellute** [comment]
@all-contributors please add @ilnaes for code

**Pull request merged**
