### PR TITLE
Send notifications when new song starts playing

### LINKED ISSUE #146: Current Playing Notifications
A feature I really enjoy in the official Spotify Client, which I would like to see in `spt` is the current playing notification. It includes the song title, artist and album art. I have been debating on which service to implement this in, whether it should go in `spt` or `spotifyd`, and figure the best and most efficient way of implementing it would be in `spt` since all of the track information is already available, and there is already an API key entangled with the service, allowing for the necessary API calls. If it were implemented in `spotifyd` instead, then a new API key would need to be generated in order to get the current playing art, info, etc. I am making this issue to solely to have this recorded somewhere, but I plan on implementing this in the nearish future. Also wanted to get any input from other contributors if you all had any other ideas/suggestions. Here is an example of what I am talking about (pardon the Christmas music in November). 
image

### PR DESCRIPTION
**Pull request by SethGower**
The official spotify client sends notifications when a new song has started playing, and I wanted to implement this feature into `spt`. This sends a notification identical to the one that Spotify sends. An example notification can be seen here. 
image

Closes #146.

### CODE REVIEW

**Review by Rigellute — CHANGES_REQUESTED** [review]
Thanks for taking a crack at this. I've left a few comments.

I also think that a feature like this should be disabled by default, and let the user enable via the config (see `src/user_config.rs`). 

Looks like there are some CI issues to be fixed too.

**Comment by SethGower** [comment]
I'll go through and make those changes. I am not sure how to fix the CI issues. If you have any suggestions, that would be great. I have been running my fork of `spt` ever since I implemented this, and it hasn't caused any issues.

**Comment by Rigellute** [comment]
Looks like there's a few merge conflicts. Are you able to resolve those?

Once you've done that, what I think I'll do is merge your fork into a side branch so I can fix the CI issues.

**Comment by SethGower** [comment]
Merge conflicts should be fixed. Still need to implement the config file features though. But that may not happen for a couple of weeks due to school work. Thanks for being patient and helping me through learning Rust. This is a really cool project and I am glad I am able to contribute.

**Comment by joaoeudes7** [comment]
@SethGower this notification is detected by playerctl?

**Comment by SethGower** [comment]
No, this isn't detected by `playerctl`. It is sent to `libnotify` by `spt` using the already existing API data. Sorry I haven't done the fixes on this yet, by the way. I have been super busy and will finish it soon.

**Comment by Rigellute** [comment]
Closing this for now, feel free to reopen if/when you get a chance to look at it again.

**Comment by mdkcore0** [comment]
was this abandoned?

**Comment by nickalcock** [comment]
A shame: I was hoping for this too :)

**Comment by SethGower** [comment]
> A shame: I was hoping for this too :)

sorry, I did in fact abandon this (for now :rofl:) I got really busy with school/work, and wasn't able to get back to this. I may pick it back up over the summer after graduation.

**Comment by nickalcock** [comment]
No problem. I might get round to it perhaps (ha ha listen to the naive idiot, only if there's a hole in the space-time continuum granting me extra hours every day).

**Pull request closed without merging**
