### PR TITLE
Playlist Editing - Import,Fork,Update,New,Delete

### PR DESCRIPTION
**Pull request by justjokiing**
I have added a few command line actions to edit playlists, mainly the import function.

This function adds all tracks from a playlist into one that you own. It keeps track of the state of the imported playlist and if it is imported again, adds any new tracks and prompts for deletion of deleted tracks. The fork function creates an identical playlist from the one prompted and does an import. The update function calls import on all of the previously imported playlists, updating them.

### CODE REVIEW

**Comment by sewnie** [comment]
I hope you didn't actually put effort into this... this project has been inactive for a long time and this most likely won't be merged.. you better be *just joking*

**Comment by justjokiing** [comment]
> I hope you didn't actually put effort into this... this project has been inactive for a long time and this most likely won't be merged.. you better be _just joking_

I am new to rust and needed the structure to implement my idea. You imagine it would be best for me to set up a project of my own?

**Comment by sewnie** [comment]
there already exists a very great project at spotify-player

**Comment by justjokiing** [comment]
> there already exists a very great project at spotify-player

I will work to migrate my code to this. Thank you.

**Pull request closed without merging**
