### PR TITLE
Added copy_album_url functionality

### PR DESCRIPTION
**Pull request by calenrobinette**
In conjunction with issue #223 

Let me know if further changes need to be made, or if anything doesn't work as intended.

### CODE REVIEW

**Comment by calenrobinette** [comment]
The only remaining issue is raised by clippy about cognitive-complexity on `pub fn handle_app` which I believe is unrelated to my changes.

**Comment by Rigellute** [comment]
Looks like we need to rejig thinks a little. I'll merge this into a side branch and fix clippy.

Thank you for your contribution 👏

**Comment by Rigellute** [comment]
https://github.com/Rigellute/spotify-tui/pull/226

**Comment by Rigellute** [comment]
@all-contributors please add @calenrobinette for code

**Pull request merged**
