### PR TITLE
Replace `clipboard` with `arboard`

### PR DESCRIPTION
**Pull request by ArturKovacs**
Replaces the unmaintained `clipboard` with [`arboard`](https://github.com/ArturKovacs/arboard)

### CODE REVIEW

**Comment by ArturKovacs** [comment]
On that note, the copy album seems to copy an invalid url to the clipboard. But I may have misunderstood something. Also I used a free account.

**Review by Rigellute — APPROVED** [review]
Looks good to me 👍

**Comment by Rigellute** [comment]
I'll merge once the conflict is fixed. Looks like you just need to keep your change and

```
pub shows_list_index: usize,
```

**Comment by ArturKovacs** [comment]
It should be ready now :)

**Comment by Rigellute** [comment]
@all-contributors please add @ArturKovacs for code

**Pull request merged**
