### PR TITLE
Handle delete key

### PR DESCRIPTION
**Pull request by synth-ruiner**
dunno that anyone else is clamouring for this, but why not, right? :)

### CODE REVIEW

**Comment by fangyi-zhou** [comment]
I think this needs to be rebased on #30 now

**Comment by Rigellute** [comment]
Ah yes, good point @fangyi-zhou.

**Comment by synth-ruiner** [comment]
Thanks- I noticed the rustfmt issue but haven't had time to add a line break! I'll rebase and fix it tonight.

**Comment by synth-ruiner** [comment]
I've tried to follow the new format, and added a test for deleting a multibyte unicode character.

funnily enough I can't actually test this at home since I don't use spotify personally! sorry :)

**Comment by Rigellute** [comment]
Looks like the commits have gone awry. 

Not sure what's gone wrong here but guessing this could be because of using `merge` rather than `rebase`? 

If things are too messed up, might be worth creating a new PR?

**Comment by synth-ruiner** [comment]
I picked rebase in my IDE but maybe it had other ideas. I'll see if I can sort it out

**Pull request closed without merging**
